import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'template/template-overview',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'template/getting-started'
        }
      ]
    },
    {
      type: 'category',
      label: 'Components',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'template/core-systems'
        }
      ]
    },
    {
      type: 'category',
      label: 'Configuration',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'template/configuration'
        }
      ]
    },
    {
      type: 'category',
      label: 'Advanced',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'template/advanced'
        }
      ]
    },
    'status'
  ]
};

export default sidebars;
